example2:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '1-23'
    min: '*'
    sec: 5,20,35,50
    cwd: '/home/user'
    user: 'user'
    command: 'echo testing timeout; sleep 10; echo timeout did not work'
    soft_timeout: 5
    hard_timeout: 7
    targets: 'G@roles:something_nonexistent or G@host:testhost1'
    target_type: compound
    number_of_targets: 2

