example3:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*'
    sec: 0,15,30,45
    cwd: '/'
    user: 'root'
    command: 'hostname; whoami; /usr/bin/touch /tmp/example_cron'
    targets: '*'
    target_type: glob
    number_of_targets: 2

