#!/usr/bin/env python3
cpu-usage-idle:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 cpu_usage_idle.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

disk-usage:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 disk_usage.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

load-rate:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 load_rate.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

mem-usage:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 mem_usage.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

replication-lag:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 replication_lag.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

replication-state:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 replication_state.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

replication-status:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 replication_status.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

vm-failed-backup:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 vm_failed_backup.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

vm-successful-backup-25h:
    year: '*'
    mon: '*'
    dow: '*'
    dom: '*'
    hour: '*'
    min: '*/2'
    sec: '*'
    cwd: '/srv/salt/alerts/files'
    user: 'root'
    command: 'python3 vm_successful_backup_25h.py -influx_host influx01.storm.lan -influx_port 8086 -influx_username admin -influx_password password -alerta_endpoint http://alerta.storm.lan/api; '
    soft_timeout: 60
    hard_timeout: 120
    targets: 'salt01*'
    target_type: compound
    number_of_targets: 0

