version: '3'

services:
    sp-master:
        build: ../
        image: saltpeter
        hostname: sp-master.sp.local
        volumes:
            - ../:/opt/saltpeter
            - ./config:/etc/saltpeter
            - ./logs:/var/log/saltpeter
        ports:
            - 8888:8888
    sp-min1:
        image: saltpeter:latest
        hostname: sp-min1.sp.local
        entrypoint: ["/usr/bin/salt-minion", "-l", "info"]
        depends_on:
            - sp-master
    sp-min2:
        image: saltpeter:latest
        hostname: sp-min2.sp.local
        entrypoint: ["/usr/bin/salt-minion", "-l", "info"]
        depends_on:
            - sp-master
