name: Publish to PyPI
on:
  push:
    tags:
     - 'master'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install wheel
    - name: Build a binary wheel
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
